name: Deploy to Stage

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  promote_to_stage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch latest commits from dev
        run: |
          git fetch origin dev

      - name: Check if JMeter tests passed on dev
        run: |
          # Aqui você pode verificar se os testes passaram corretamente na branch dev
          # (por exemplo, se o commit foi marcado com sucesso em algum log ou tag)
          echo "Testes JMeter passaram na branch dev."
          
      - name: Extract Medatada
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
         images: reginaabarbara/devops-backend-new    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.USER }} 
          password: ${{ secrets.PASS }}  

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          build-args: |
            MODE=${{ github.ref_name }}
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{  steps.meta.outputs.labels  }}
      
      - name: Fazer o merge da branch dev na branch stage
        run: |
          git checkout stage
          git merge dev
          git push origin stage

      - name: Confirmar deploy para stage
        run: |
          echo "Aplicação implantada com sucesso na branch Stage com a tag da imagem 
